name: Hotfix - Pull Request
on:
  pull_request:
    branches: [ 'release/**' ]
    types: [opened, synchronize, reopened, closed, labeled, unlabeled]

jobs:
  default:
    uses: cloudposse/example-github-action-release-workflow/.github/workflows/reusable-hotfix-pull-request.yml@main
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
##
##  Example how to use private shared actions
##
#    secrets:
#      github-pat: "${{ secrets.ADMIN_GITHUB_TOKEN }}"
