name: Bleeding edge
on:
  push:
    branches: [ main ]

jobs:
  default:
    uses: cloudposse/example-github-action-release-workflow/.github/workflows/reusable-main.yml@main
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"

