name: Release
on:
  release:
    types: [published]

jobs:
  default:
    uses: cloudposse/example-github-action-release-workflow/.github/workflows/reusable-release.yml@main
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
##
##  Example how to use private shared actions
##
#    secrets:
#      github-pat: "${{ secrets.ADMIN_GITHUB_TOKEN }}"
