name: Reusable - Pull Request
on:
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
      repository:
        required: true
        type: string
      registry:
        description: "Docker registry"
        required: false
        type: string
        default: registry.hub.docker.com
      open:
        required: true
        type: boolean
        default: true
      labels:
        required: true
        type: string
      ref:
        required: true
        type: string
##
##  Example how to use private shared actions
##
#    secrets:
#      github-pat:
#        required: true

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

##
##  Example how to use private shared actions
##
#      - name: Checkout private actions
#        uses: actions/checkout@v2
#        with:
#          repository: ${{ inputs.organization }}/github
#          token: ${{ secrets.github-pat }}
#          path: github

      - name: Controller
        uses: ./github-shared-actions/actions/preview_controller
        id: controller
        with:
          labels: ${{ inputs.labels }}
          open: ${{ inputs.open }}
          env-label: |
            preview: deploy
            qa1: deploy/qa1
            qa2: deploy/qa2
            qa3: deploy/qa3
            qa4: deploy/qa4

    outputs:
      namespace: ${{ inputs.ref }}
      labels_env: ${{ steps.controller.outputs.labels_env }}
      deploy_envs: ${{ steps.controller.outputs.deploy_envs }}
      destroy_envs: ${{ steps.controller.outputs.destroy_envs }}

  build:
    runs-on: ubuntu-latest
    if: ${{ inputs.open }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
##
##  Example how to use private shared actions
##
#      - name: Checkout private actions
#        uses: actions/checkout@v2
#        with:
#          repository: ${{ inputs.organization }}/github
#          token: ${{ secrets.github-pat }}
#          path: github

      - name: Build
        id: build
        uses: ./github-shared-actions/actions/build
        with:
          organization: ${{ inputs.organization }}
          repository: ${{ inputs.repository }}
          registry: ${{ inputs.registry }}

    outputs:
      image: ${{ steps.build.outputs.image }}
      tag: ${{ steps.build.outputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    if: ${{ needs.context.outputs.deploy_envs != '[]'  }}
    strategy:
      matrix:
        env: ${{ fromJson(needs.context.outputs.deploy_envs) }}
    environment:
      name: ${{ matrix.env }}
      url: ${{ steps.deploy.outputs.webapp-url }}
    needs: [ context, build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
##
##  Example how to use private shared actions
##
#      - name: Checkout private actions
#        uses: actions/checkout@v2
#        with:
#          repository: ${{ inputs.organization }}/github
#          token: ${{ secrets.github-pat }}
#          path: github-shared-actions

      - name: Deploy
        uses: ./github-shared-actions/actions/deploy
        id: deploy
        with:
          stack: dev
          environment: ${{ matrix.env }}
          namespace: ${{ needs.context.outputs.namespace }}
          image: ${{ needs.build.outputs.image }}
          image-tag: ${{ needs.build.outputs.tag }}
          operation: deploy
##
##  Example how to use private shared actions
##
#          github-pat: ${{ secrets.github-pat }}

  destroy:
    runs-on: ubuntu-latest
    if: ${{ needs.context.outputs.destroy_envs != '[]'  }}
    strategy:
      matrix:
        env: ${{ fromJson(needs.context.outputs.destroy_envs) }}
    needs: [ context ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./github-shared-actions/actions/get_deployment
        id: deployment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          env-name: ${{ matrix.env }}
          ref-to-search: ${{ inputs.ref}}
          status: success

##  Example how to use private shared actions
##
#      - name: Checkout private actions
#        uses: actions/checkout@v2
#        with:
#          repository: ${{ inputs.organization }}/github
#          token: ${{ secrets.github-pat }}
#          path: github-shared-actions

      - name: Destroy
        uses: ./github-shared-actions/actions/deploy
        if: ${{ steps.deployment.outputs.deploymentId != '' }}
        id: deploy
        with:
          stack: dev
          environment:  ${{ matrix.env }}
          namespace: ${{ needs.context.outputs.namespace }}
          image: "<none>"
          image-tag: "<none>"
          operation: destroy
##
##  Example how to use private shared actions
##
#          github-pat: ${{ secrets.github-pat }}

      - name: Cleanup labels
        uses: ./github-shared-actions/actions/preview_controller_label_cleanup
        if: ${{ ! inputs.open }}
        with:
          labels_env: ${{ needs.context.outputs.labels_env }}
          env: ${{ matrix.env }}

      - uses: chrnorm/deployment-status@v2.0.0
        if: ${{ steps.deployment.outputs.deploymentId != '' }}
        with:
          state: inactive
          token: ${{ github.token }}
          deployment-id: ${{ steps.deployment.outputs.deploymentId }}
