name: Reusable - Hotfix
on:
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
      repository:
        required: true
        type: string
      registry:
        description: "Docker registry"
        required: false
        type: string
        default: registry.hub.docker.com
##
##  Example how to use private shared actions
##
#    secrets:
#      github-pat:
#        required: true

env:
  ORGANIZATION: ${{ inputs.organization }}
  ACTION_REPO_NAME: ${{ inputs.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
##
##  Example how to use private shared actions
##
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          repository: ${{ inputs.organization }}/github-shared-actions
#          token: ${{ secrets.github-pat }}
#          path: github-shared-actions

      - name: Build
        id: build
        uses: ./github-shared-actions/actions/build
        with:
          organization: ${{ inputs.organization }}
          repository: ${{ inputs.repository }}
          registry: ${{ inputs.registry }}

    outputs:
      image: ${{ steps.build.outputs.image }}
      tag: ${{ steps.build.outputs.tag }}

  release:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: rui-costa/action-automatic-semver-releases@1.1.0
        with:
          TOKEN: ${{ github.token }}
          SEMVER: PATCH

#      - name: Increment Step Patch
#        id: increment-semver-patch
#        uses: Benbentwo/increment-semver@1.0.8
#        with:
#          version-level: '-p'
