name: Reusable - Release
on:
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
      repository:
        required: true
        type: string
      registry:
        description: "Docker registry"
        required: false
        type: string
        default: registry.hub.docker.com
##
##  Example how to use private shared actions
##
#    secrets:
#      github-pat:
#        required: true

env:
  ORGANIZATION: ${{ inputs.organization }}
  ACTION_REPO_NAME: ${{ inputs.repository }}

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - shell: sh
        run: echo "Promote docker image ${{ inputs.registry }}/${{ inputs.repository }}:sha-${{ github.sha }} to ${{ inputs.registry }}/${{ inputs.repository }}:${{ github.event.release.tag_name }}"
#      - uses: EuphoricSystems/docker-promote-image@1.0.0
#        with:
#          src: ${{ inputs.registry }}/${{ inputs.repository }}:sha-${{ github.sha }}
#          destinations: ${{ inputs.registry }}/${{ inputs.repository }}:${{ github.event.release.tag_name }}
    outputs:
      image: ${{ inputs.registry }}/${{ inputs.repository }}
      tag: ${{ github.event.release.tag_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: [ promote ]
    steps:
##
##  Example how to use private shared actions
##
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          repository: ${{ inputs.organization }}/github
#          token: ${{ secrets.github-pat }}
#          path: github

      - name: Deploy
        uses: ./github-shared-actions/actions/deploy
        with:
          stack: dev
          environment:  production
          namespace: production
          image: ${{ needs.promote.outputs.image }}
          image-tag: ${{ needs.promote.outputs.tag }}
          operation: apply
##
##  Example how to use private shared actions
##
#          github-pat: ${{ secrets.github-pat }}
